name: 'demo'
version: '1.0.0'
config-version: 2

profile: 'dbt_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  demo:
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  demo:
    +schema: reference``