dbt_demo:
  outputs:

    dev:
      dbname: dwh
      host: localhost
      pass: dbt_demo
      port: 5432
      schema: demo
      threads: 1
      type: postgres
      user: dbt_demo

    prod:
      dbname: ...
      host: ...
      pass: ...
      port: ...
      schema: ...
      threads: ...
      type: ...
      user: ...

  target: dev
