CREATE USER dbt_demo WITH PASSWORD 'dbt_demo';

CREATE DATABASE dwh;

GRANT ALL PRIVILEGES ON DATABASE dwh TO dbt_demo;

\connect dwh;

CREATE SCHEMA IF NOT EXISTS demo AUTHORIZATION dbt_demo;

-- CREATE SCHEMA IF NOT EXISTS staging AUTHORIZATION dbt_demo;

-- CREATE SCHEMA IF NOT EXISTS marts AUTHORIZATION dbt_demo;